import { RoleKey } from "@prisma/client";

/**
 * Central permission catalog. Every module's routes declare which of these
 * keys they require via the `authorize()` middleware. This is the single
 * source of truth seeded into the `permissions` table (see prisma/seed.ts)
 * and referenced by role → permission mappings below.
 *
 * Naming convention: "<module>:<action>". A role holding "*:*" bypasses all
 * checks (Super Admin only).
 */
export const PERMISSIONS = {
  ALL: "*:*",

  LEAD_VIEW: "lead:view",
  LEAD_CREATE: "lead:create",
  LEAD_UPDATE: "lead:update",
  LEAD_DELETE: "lead:delete",
  LEAD_ASSIGN: "lead:assign",
  LEAD_CONVERT: "lead:convert",

  CAMPAIGN_VIEW: "campaign:view",
  CAMPAIGN_MANAGE: "campaign:manage",

  ACTIVITY_VIEW: "activity:view",
  ACTIVITY_CREATE: "activity:create",

  CALENDAR_VIEW: "calendar:view",
  CALENDAR_MANAGE: "calendar:manage",

  APPROVAL_VIEW: "approval:view",
  APPROVAL_DECIDE: "approval:decide",

  CUSTOMER_VIEW: "customer:view",
  CUSTOMER_CREATE: "customer:create",
  CUSTOMER_UPDATE: "customer:update",
  CUSTOMER_MERGE: "customer:merge",

  OPPORTUNITY_VIEW: "opportunity:view",
  OPPORTUNITY_CREATE: "opportunity:create",
  OPPORTUNITY_UPDATE: "opportunity:update",
  OPPORTUNITY_CHANGE_STAGE: "opportunity:change_stage",

  QUOTATION_VIEW: "quotation:view",
  QUOTATION_CREATE: "quotation:create",
  QUOTATION_UPDATE: "quotation:update",
  QUOTATION_SEND: "quotation:send",
  QUOTATION_OVERRIDE_PRICE: "quotation:override_price",
  QUOTATION_APPROVE: "quotation:approve",

  CUSTOMER_PO_VIEW: "customer_po:view",
  CUSTOMER_PO_CREATE: "customer_po:create",

  SALES_ORDER_VIEW: "sales_order:view",
  SALES_ORDER_MANAGE: "sales_order:manage",

  INVENTORY_VIEW: "inventory:view",
  INVENTORY_ALLOCATE: "inventory:allocate",
  INVENTORY_ADJUST: "inventory:adjust",

  PROCUREMENT_VIEW: "procurement:view",
  PROCUREMENT_MANAGE: "procurement:manage",

  PROJECT_VIEW: "project:view",
  PROJECT_MANAGE: "project:manage",
  PROJECT_APPROVE_GOLIVE: "project:approve_golive",

  TASK_VIEW: "task:view",
  TASK_UPDATE: "task:update",

  DEVICE_VIEW: "device:view",
  DEVICE_MANAGE: "device:manage",

  FINANCE_VIEW: "finance:view",
  FINANCE_INVOICE_MANAGE: "finance:invoice_manage",
  FINANCE_PAYMENT_RECORD: "finance:payment_record",

  SUPPORT_VIEW: "support:view",
  SUPPORT_MANAGE: "support:manage",

  AMC_VIEW: "amc:view",
  AMC_MANAGE: "amc:manage",

  REPORTS_VIEW: "reports:view",
  REPORTS_EXECUTIVE: "reports:executive",

  AI_ASSISTANT_USE: "ai_assistant:use",

  SETTINGS_MANAGE_ROLES: "settings:manage_roles",
  SETTINGS_MANAGE_ORG: "settings:manage_org",
  SETTINGS_MANAGE_CATALOG: "settings:manage_catalog",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Default role → permission matrix, applied on first seed. Super Admin can
 * edit any role's permissions afterward via Settings > Roles — this table is
 * a starting point, not a hardcoded ceiling.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<RoleKey, PermissionKey[]> = {
  SUPER_ADMIN: [PERMISSIONS.ALL],

  MANAGING_DIRECTOR: [
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.OPPORTUNITY_VIEW,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.QUOTATION_APPROVE,
    PERMISSIONS.SALES_ORDER_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.AMC_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXECUTIVE,
    PERMISSIONS.AI_ASSISTANT_USE,
    PERMISSIONS.CAMPAIGN_VIEW,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.APPROVAL_VIEW,
    PERMISSIONS.APPROVAL_DECIDE,
    PERMISSIONS.ACTIVITY_VIEW,
  ],

  SALES_DIRECTOR: [
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_ASSIGN,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.OPPORTUNITY_VIEW,
    PERMISSIONS.OPPORTUNITY_UPDATE,
    PERMISSIONS.OPPORTUNITY_CHANGE_STAGE,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.QUOTATION_APPROVE,
    PERMISSIONS.SALES_ORDER_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AI_ASSISTANT_USE,
    PERMISSIONS.CAMPAIGN_VIEW,
    PERMISSIONS.CAMPAIGN_MANAGE,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_MANAGE,
    PERMISSIONS.APPROVAL_VIEW,
    PERMISSIONS.APPROVAL_DECIDE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.ACTIVITY_CREATE,
  ],

  SALES_MANAGER: [
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_ASSIGN,
    PERMISSIONS.LEAD_CONVERT,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_MERGE,
    PERMISSIONS.OPPORTUNITY_VIEW,
    PERMISSIONS.OPPORTUNITY_CREATE,
    PERMISSIONS.OPPORTUNITY_UPDATE,
    PERMISSIONS.OPPORTUNITY_CHANGE_STAGE,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.QUOTATION_UPDATE,
    PERMISSIONS.QUOTATION_SEND,
    PERMISSIONS.QUOTATION_APPROVE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AI_ASSISTANT_USE,
    PERMISSIONS.CAMPAIGN_VIEW,
    PERMISSIONS.CAMPAIGN_MANAGE,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_MANAGE,
    PERMISSIONS.APPROVAL_VIEW,
    PERMISSIONS.APPROVAL_DECIDE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.ACTIVITY_CREATE,
  ],

  SALES_EXECUTIVE: [
    PERMISSIONS.LEAD_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_CONVERT,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.OPPORTUNITY_VIEW,
    PERMISSIONS.OPPORTUNITY_CREATE,
    PERMISSIONS.OPPORTUNITY_UPDATE,
    PERMISSIONS.OPPORTUNITY_CHANGE_STAGE,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.QUOTATION_CREATE,
    PERMISSIONS.QUOTATION_UPDATE,
    PERMISSIONS.QUOTATION_SEND,
    PERMISSIONS.CUSTOMER_PO_VIEW,
    PERMISSIONS.CUSTOMER_PO_CREATE,
    PERMISSIONS.AI_ASSISTANT_USE,
    PERMISSIONS.CAMPAIGN_VIEW,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_MANAGE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.ACTIVITY_CREATE,
  ],

  PRE_SALES_ENGINEER: [
    PERMISSIONS.OPPORTUNITY_VIEW,
    PERMISSIONS.OPPORTUNITY_UPDATE,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_MANAGE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.ACTIVITY_CREATE,
  ],

  TECHNICAL_CONSULTANT: [
    PERMISSIONS.OPPORTUNITY_VIEW,
    PERMISSIONS.OPPORTUNITY_UPDATE,
    PERMISSIONS.QUOTATION_VIEW,
    PERMISSIONS.QUOTATION_UPDATE,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_MANAGE,
    PERMISSIONS.ACTIVITY_VIEW,
    PERMISSIONS.ACTIVITY_CREATE,
  ],

  PROJECT_MANAGER: [
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_MANAGE,
    PERMISSIONS.PROJECT_APPROVE_GOLIVE,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.DEVICE_VIEW,
    PERMISSIONS.DEVICE_MANAGE,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  IMPLEMENTATION_ENGINEER: [
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.DEVICE_VIEW,
    PERMISSIONS.DEVICE_MANAGE,
    PERMISSIONS.PROJECT_VIEW,
  ],

  SUPPORT_ENGINEER: [
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.SUPPORT_MANAGE,
    PERMISSIONS.DEVICE_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
  ],

  FINANCE: [PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_INVOICE_MANAGE, PERMISSIONS.REPORTS_VIEW],

  ACCOUNTS: [PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_PAYMENT_RECORD, PERMISSIONS.REPORTS_VIEW],

  WAREHOUSE: [PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_ALLOCATE, PERMISSIONS.INVENTORY_ADJUST],

  PROCUREMENT: [PERMISSIONS.PROCUREMENT_VIEW, PERMISSIONS.PROCUREMENT_MANAGE, PERMISSIONS.INVENTORY_VIEW],

  // Deliberately empty: a portal user's access is bounded entirely by the
  // /api/v1/portal/* namespace (gated on req.auth.customerId being set, see
  // modules/portal/portal.routes.ts), not by these RBAC permission flags.
  // Internal-module view permissions (QUOTATION_VIEW etc.) were granted here
  // previously, which would have let a portal user call the *internal*,
  // company-wide /quotations, /purchase-orders, /projects, /finance,
  // /support endpoints and see every customer's data, not just their own —
  // those endpoints only scope by companyId, never by customerId.
  CUSTOMER_PORTAL_USER: [],
};
